language: php

sudo: false

php:
  - 5.6
  - 7.0

branches:
  only:
  - master

before_install: composer self-update

install: composer install

script:
  - composer validate
  - phpunit --testdox
#script: phpunit --coverage-text
